### ISSUE TITLE
Installing django-oauth-toolkit-jwt on Windows failed because of cryptography==2.7 requirements

### ISSUE THREAD

**Issue by LodrikMtl** [Humanitec/django-oauth-toolkit-jwt#25]
I can install cryptography 2.8 easily but not cryptography 2.7. It would be nice to accept upper version. What do you think?

**Comment by TM2500** [comment]
I'm currently in the process of moving this library to the post Py2.7-era.
So I'm working on updating the dependencies and such things.
Please be a bit patient till this is done.
Otherwise, please consult [the cryptography docs](https://cryptography.io) for build/install problems of their library.

**Comment by LodrikMtl** [comment]
Good news! Thx for your time
